### ISSUE TITLE
Cannot run example

### ISSUE THREAD

**Issue by sscarduzio** [WPSemantix/timbr_python_SQLAlchemy#1]
Hello, I use docker for ease of reproducing the issue:

Dockerfile
```
FROM python:3.9-slim
RUN apt-get update && apt-get install -y git krb5-config gcc g++ libkrb5-dev libsasl2-dev
RUN git clone "https://github.com/WPSemantix/timbr_python_SQLAlchemy.git" timbr_driver
WORKDIR ./timbr_driver
RUN pip install -r requirements.txt
COPY test.py .
CMD python test.py
```

test.py
```python
from sqlalchemy import create_engine
from TCLIService.ttypes import TOperationState
# Create new sqlalchemy connection
engine = create_engine(f"timbr+http://token@os_ontology:tk_@127.0.0.1:11000", connect_args={'configuration': {'set:hiveconf:hiveMetadata': 'true'}})
conn = engine.connect()
dbapi_conn = engine.raw_connection()
cursor = dbapi_conn.cursor()

# Use the connection to execute a query
query = "SHOW CONCEPTS"
cursor.execute(query)

# Check the status of this execution
status = cursor.poll().operationState
while status in (TOperationState.INITIALIZED_STATE, TOperationState.RUNNING_STATE):
  status = cursor.poll().operationState

results = cursor.fetchall()
print(results)
```

Output
```
 docker run -t timbrtest
Traceback (most recent call last):
  File "/timbr_driver/test.py", line 4, in <module>
    engine = create_engine(f"timbr+http://token@os_ontology:tk_ffca8f55034a5b4cff6c9013a2a84b4eb7b7e0f38cbbada7b60f7804484d0267@127.0.0.1:11000", connect_args={'configuration': {'set:hiveconf:hiveMetadata': 'true'}})
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 552, in create_engine
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/url.py", line 754, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 368, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:timbr.http
```

**Comment by amitwps** [comment]
Check SQLAlchemy version
